language: python
python:
  - "3.5"
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
# command to run tests
script:
  - python asmde/parser.py --input examples/test_basic.S
  - python asmde/parser.py --input examples/test_basic_2.S
